# Generated by Django 5.2 on 2025-04-06 23:56

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_publicscanitem_publicstillitem_publicvideoitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientDeliverableAdminView",
            fields=[],
            options={
                "verbose_name": "Client Deliverable",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.clientdeliverable",),
        ),
    ]
