# Generated by Django 5.2 on 2025-04-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_remove_newspost_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspost",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional featured image for the post.",
                null=True,
                upload_to="news_images/",
            ),
        ),
    ]
