# Generated by Django 5.2 on 2025-04-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_newspost_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspost",
            name="content",
            field=models.TextField(
                blank=True, help_text="Main content of the post.", null=True
            ),
        ),
    ]
