# Generated by Django 5.2 on 2025-04-05 13:54

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_alter_newspost_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspost",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, null=True, verbose_name="Content"
            ),
        ),
    ]
