# Generated by Django 5.2 on 2025-04-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0007_delete_article"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newspost",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                db_index=True,
                default="draft",
                max_length=10,
            ),
        ),
    ]
