# Generated by Django 5.2 on 2025-04-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SlideshowImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="slideshow/")),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Descriptive text for screen readers (optional but recommended).",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "slideshow_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in slideshow (lower numbers appear first).",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Slideshow Image",
                "verbose_name_plural": "Slideshow Images",
                "ordering": ["slideshow_order", "-uploaded_at"],
            },
        ),
    ]
