# Generated by Django 5.2 on 2025-04-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visualizationproject",
            name="type",
        ),
        migrations.AddField(
            model_name="visualizationproject",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("scan", "3D Scan"),
                    ("video", "Video Visualization"),
                    ("still", "Still Image"),
                ],
                db_index=True,
                default="still",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="VisualizationType",
        ),
    ]
