# Generated by Django 5.2 on 2025-04-06 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_visualizationproject_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicPortfolioItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("scan", "3D Scan"),
                            ("video", "Video Visualization"),
                            ("still", "Still Image"),
                        ],
                        db_index=True,
                        default="still",
                        max_length=10,
                    ),
                ),
                ("embed_code", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="portfolio/")),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Public Portfolio Item",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClientDeliverable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("scan", "3D Scan"),
                            ("video", "Video Visualization"),
                            ("still", "Still Image"),
                            ("other", "Other Deliverable"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("embed_code", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="client_deliverables/%Y/%m/%d/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverables",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Deliverable",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="VisualizationProject",
        ),
    ]
