# Generated by Django 5.2 on 2025-04-06 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_publicportfolioitem_clientdeliverable_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicScanItem",
            fields=[],
            options={
                "verbose_name": "Public 3D Scan",
                "verbose_name_plural": "AA Public 3D Scans",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.publicportfolioitem",),
        ),
        migrations.CreateModel(
            name="PublicStillItem",
            fields=[],
            options={
                "verbose_name": "Public Still Image",
                "verbose_name_plural": "AC Public Stills",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.publicportfolioitem",),
        ),
        migrations.CreateModel(
            name="PublicVideoItem",
            fields=[],
            options={
                "verbose_name": "Public Video Visualization",
                "verbose_name_plural": "AB Public Videos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.publicportfolioitem",),
        ),
    ]
