# Generated by Django 5.2 on 2025-04-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_publicscanitem_publicstillitem_publicvideoitem"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="publicscanitem",
            options={
                "verbose_name": "Public 3D Scan",
                "verbose_name_plural": "Public 3D Scans",
            },
        ),
        migrations.AlterModelOptions(
            name="publicstillitem",
            options={
                "verbose_name": "Public Still Image",
                "verbose_name_plural": "Public Stills",
            },
        ),
        migrations.AlterModelOptions(
            name="publicvideoitem",
            options={
                "verbose_name": "Public Video Visualization",
                "verbose_name_plural": "Public Videos",
            },
        ),
        migrations.AddField(
            model_name="clientdeliverable",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("client_review", "Pending Client Review"),
                    ("approved", "Approved"),
                ],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="publicportfolioitem",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                db_index=True,
                default="draft",
                max_length=10,
            ),
        ),
    ]
