# Generated by Django 5.2 on 2025-04-07 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_publicscanitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientdeliverable",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                db_index=True,
                default="draft",
                max_length=20,
            ),
        ),
    ]
