# Generated by Django 5.2 on 2025-04-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_clientdeliverable_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicportfolioitem",
            name="is_featured",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Check to feature this item in the homepage slideshow.",
            ),
        ),
        migrations.AddField(
            model_name="publicportfolioitem",
            name="slideshow_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Order in the slideshow (lower numbers appear first).",
            ),
        ),
    ]
