# Generated by Django 5.2 on 2025-04-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_publicportfolioitem_is_featured_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publicportfolioitem",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="publicportfolioitem",
            name="slideshow_order",
        ),
    ]
